import type { Metadata } from "next";
import Link from 'next/link';
import { Geist, Geist_Mono, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import {
  Menubar,
  MenubarContent,
  MenubarItem,
  MenubarMenu,
  MenubarSeparator,
  MenubarShortcut,
  MenubarTrigger,
} from "@/components/ui/menubar"
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faGithub, faLinkedin } from "@fortawesome/free-brands-svg-icons";
import { faPaperPlane } from "@fortawesome/free-solid-svg-icons";

import { Button } from "@/components/ui/button"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const robotoCondensed = Roboto_Condensed({
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoCondensed.className} antialiased `}
      >
        <header>
          <Menubar className="m-0 rounded-none bg-white">
            <MenubarMenu>
              <MenubarTrigger className="text-lg text-black bg-transparent focus:bg-transparent data-[state=open]:bg-transparent hover:bg-transparent active:bg-transparent md:flex-row md:justify-between">
                <Link href="#inicio" className="bg-transparent">Inicio</Link>
              </MenubarTrigger>

              <MenubarTrigger className="text-lg text-black bg-transparent focus:bg-transparent data-[state=open]:bg-transparent hover:bg-transparent active:bg-transparent">
                <Link href="#Educacion" className="bg-transparent">Educación</Link>
              </MenubarTrigger>

              <MenubarTrigger className="text-lg text-black bg-transparent focus:bg-transparent data-[state=open]:bg-transparent hover:bg-transparent active:bg-transparent">
                <Link href="#Proyectos" className="bg-transparent">Proyectos</Link>
              </MenubarTrigger>
            </MenubarMenu>

          </Menubar>
        </header>
        {children}
        <footer className="mt-2 bg-gradient-to-b from-gray-800 to-gray-900 text-white py-6">
          <div className=" grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-1 px-4">

            {/* Redes */}
            <div className="flex flex-col items-center rounded-2xl p-4 shadow-md">
              <p className="text-lg font-semibold mb-3">Redes</p>
              <div className="flex flex-row gap-3 text-3xl text-white items-center justify-center">
                <Link href="https://github.com/javierR26" target="_blank" className="w-7 h-7">
                  <FontAwesomeIcon icon={faGithub} />
                </Link>
                <Link href="https://linkedin.com/in/edison-cárdenas-a0b05a307" target="_blank" className="w-7 h-7">
                  <FontAwesomeIcon icon={faLinkedin} />
                </Link>
                <Link href="/formulario" target="_blank" className="w-7 h-7">
                  <FontAwesomeIcon icon={faPaperPlane} />
                </Link>
              </div>
            </div>


            {/* Menú */}
            <div className="flex flex-col justify-center items-center  rounded-2xl shadow-md">
              <p className="text-lg font-semibold ">Menu</p>
              <Menubar className="m-0 ">
                <MenubarMenu>
                  <MenubarTrigger className="text-lg text-black bg-transparent focus:bg-transparent data-[state=open]:bg-transparent hover:bg-transparent active:bg-transparent">
                    <Link href="#inicio" className="bg-transparent">Inicio</Link>
                  </MenubarTrigger>

                  <MenubarTrigger className="text-lg text-black bg-transparent focus:bg-transparent data-[state=open]:bg-transparent hover:bg-transparent active:bg-transparent">
                    <Link href="#Educacion" className="bg-transparent">Educación</Link>
                  </MenubarTrigger>

                  <MenubarTrigger className="text-lg text-black bg-transparent focus:bg-transparent data-[state=open]:bg-transparent hover:bg-transparent active:bg-transparent">
                    <Link href="#Proyectos" className="bg-transparent">Proyectos</Link>
                  </MenubarTrigger>
                </MenubarMenu>

              </Menubar>
            </div>

            {/* Hoja de vida */}
            <div className="flex flex-col justify-center items-center  rounded-2xl shadow-md">
              <p className="text-lg font-semibold mb-3">Descargar Hoja de vida</p>
              <Link href="/doc/hoja_v.pdf" download={"Edison_Cardenas.pdf"} className="bg-white p-2 rounded-2xl border-white text-black hover:bg-gray-200 hover:text-gray-900 transition-all">
                Descargar
              </Link>
            </div>

          </div>
        </footer>

      </body>
    </html>
  );
}
